title: CHANGELOG
repository_url: ""

sections:
  - title: "âœ¨ æ–°åŠŸèƒ½"
    commits:
      - feat
  - title: "ğŸ› ä¿®å¤"
    commits:
      - fix
  - title: "ğŸ§¼ é‡æ„"
    commits:
      - refactor
  - title: "ğŸ“š æ–‡æ¡£"
    commits:
      - docs
  - title: "ğŸ¨ æ ·å¼"
    commits:
      - style
  - title: "ğŸ”§ æ‚é¡¹"
    commits:
      - chore
  - title: "ğŸ§ª æµ‹è¯•"
    commits:
      - test
  - title: "âš¡ æ€§èƒ½"
    commits:
      - perf
  - title: "ğŸ’¥ é‡å¤§å˜æ›´"
    commits:
      - BREAKING CHANGE

commit_groups:
  title_maps:
    feat: æ–°åŠŸèƒ½
    fix: ä¿®å¤

templates:
  commit: |
    - {{.Subject}}
  commit_empty: |
    - æ— 
  footer: |
    ---
    _ç”± [git-chglog](https://github.com/git-chglog/git-chglog) è‡ªåŠ¨ç”Ÿæˆ_
  header: |
    # æ›´æ–°æ—¥å¿—

    æœ¬æ–‡ä»¶è®°å½•äº†é¡¹ç›®çš„æ‰€æœ‰é‡è¦å˜æ›´ã€‚
  template: CHANGELOG.md.tmpl

